language: ruby

sudo: false

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - 2.2.0
  - ruby-head
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7

before_script:
  - mysql -e 'create database kaui_test;'
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec rake test:units

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  - MYSQL_PASSWORD='' MYSQL_USER='travis'

#force travis to use only 'bundle install' instead of 'bundle install --deployments'
bundler_args: ''
