language: ruby

notifications:
  email:
    - killbilling-dev@googlegroups.com

rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - 1.8.7

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

before_script:
  - mysql -e 'create database kaui_test;'

script:
  - pushd test/dummy && RAILS_ENV=test bundle exec rake db:migrate --trace && RAILS_ENV=test bundle exec rake db:test:prepare && popd
  - bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  - MYSQL_PASSWORD=''

#force travis to use only 'bundle install' instead of 'bundle install --deployments'
bundler_args: ''
